Dev
RoKenshi/CurrencyConverter pull request #1
Opened 2023-11-07 13:15 UTC by RoKenshi

my first pull request

2023-11-07 14:00 UTC, kegisa requested changes

2023-11-07 14:00 UTC, kegisa commented on pom.xml
> +        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
А для чего это здесь?

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/QouterApp.java
> +import org.example.service.*;
Импорты лучше разворачивать, это можно настрои ть в идее. А то некоторые классы называются одинаково и хз что ты там импортнул.

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/Main.java
> +        new QouterApp().run();
Здесь как обговаривали должно быть создание объектов всех реалоизаций всех классов и инжект их к объект основной логики приложения

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/Main.java
> +public class Main {
отступы

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/Main.java
> +package org.example;
Пакет нужно нормальнго назвать

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/QouterApp.java
> +    RatesGetter ratesGetter;
Модификаторы доступа

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/QouterApp.java
> +public class QouterApp {
Класс нужно нормальнго назвать, если этот класс содержит основную логику приложения то MainLogicService  или что то вроде

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/QouterApp.java
> +    public QouterApp() {
Зависимости должны инжектится черзе констурктор

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/QouterApp.java
> +    void run() {
Модификатор доступа

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/QouterApp.java
> +        try {
Использование нескольких траев выглядит странно, можно же просто всю логику этого метода обмотать в трай кетч. И возможно нужно это сделать в бесконечном цикле, если вдруг ошибка просто в кетче выводить ифну юзеру и продолжать цикл

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/QouterApp.java
> +            System.out.println("Баланс не может быть отрицательным");
Вывод должен быть не в консоль а пользователю, если нужно что то залогировать то добавляй логгер отдельно

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/QouterApp.java
> +            if (!userWallet.getTypeQouter().equals("usd") && userWallet.getTypeQouter().equals("eur")) {
что то странное, не варен доллары и равен евро тогда ошибка, и вообще опять не расширяемое приложение, лучше проверять что пользователь ввел валюту которая есть в доступных(те что загрузили из файла)

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/QouterApp.java
> +            System.out.println(answer);
вывод надо делать черзе интерфейс взаимодействия с юзером

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/model/Rates.java
> +    private double usd;
Валюты могут быть разные, лучше не завязваться только на две, нужна модель где будет имя валюты и ее курс

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/model/UserWallet.java
> +    public UserWallet() {
конструктор по умолчнию и так есть уже, не нужно его явно объявлять

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/model/UserWallet.java
> +public class UserWallet {
Вообще кажется какой то лишний класс, мы можем просто получить от пользователя суммы которую он хочет конверунть в double, потом получить валюту как string и затем посто найти курс валюты нужной в моделе rates или в мапе какой то. и передать в метод конвертора курс, сумму и конвертер вернет сумму в нужной валюте

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/service/ConverterCurrencyService.java
> +    Rates rates;
Модификатор доступа

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/service/ConverterCurrencyService.java
> +    public ConverterCurrencyService(Rates rates) {
Конвертеру не обязательно знать курсы валют всех, достаточно просто в метод по конвертирвоания передать курс и все

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/service/ConverterCurrencyService.java
> +    public Double convertCurrency(UserWallet userWallet) {
Модель в параметрах лишняя, сделай лучше логику как я описал, в параметрах будут приходить сумма котоую надо перевести(в рублях) и курс , конвертер просто будет делить и все

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/service/ConverterCurrencyService.java
> +    public Double typeCurrency(String typeCurrency){
Этой логики в конвертер еуже не будет, когда ты сделаешь изменения которая я выше описал

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/service/RatesGetter.java
> +    Rates getCurrentRates() throws FileNotFoundException;
насчет исключений уже разобрались что надо это убрать

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/service/RatesGetterFromFile.java
> +    private static final String FILE_PATH = "./src/main/resources/opt/quoter2.json";
отступы

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/service/RatesGetterFromFile.java
> +    private static final String FILE_PATH = "./src/main/resources/opt/quoter2.json";
сейчас путь до файла у тебя захардкожен , это плохо, путь лучше передвать извне в объект. Идеально через констуртор, тогда ты сможешь поменять путь до файла не меняя класс. А значит не нарушишь солид

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/service/RatesGetterFromFile.java
> +    public Rates getCurrentRates() throws FileNotFoundException {
Хороший метод

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/service/UserInput.java
> +public interface UserInput {
Ага, как я и просил

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/service/UserInputImpl.java
> +public class UserInputImpl implements UserInput {
Здесь название лучше попроавить , по сути это консольный интерфейс, лучше так и называть   consoleUserInput

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/service/UserInputImpl.java
> +        Scanner scanner = new Scanner(System.in);
так у тебя сканнер будет создаваться каждый вызов метода, вынеси его в поля класса и созвдавать в констуркторе

2023-11-07 14:00 UTC, kegisa commented on src/main/java/org/example/service/UserInteraction.java
> +public class UserInteraction {
какой то лишний класс, распарсить ты это можешь и в классе основной логики, ничего страшного в этом нет

2023-11-07 16:13 UTC, RoKenshi commented on pom.xml
> +        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
Помник не нужен?

2023-11-07 16:14 UTC, RoKenshi commented on src/main/java/org/example/Main.java
> +package org.example;
Сделано

2023-11-07 16:22 UTC, RoKenshi commented on src/main/java/org/example/QouterApp.java
> +    RatesGetter ratesGetter;
ok

2023-11-07 16:22 UTC, RoKenshi commented on src/main/java/org/example/QouterApp.java
> +public class QouterApp {
ok

2023-11-07 16:24 UTC, kegisa commented on pom.xml
> +        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
вопрос к конкретной строчке , не к помнику

2023-11-07 16:24 UTC, RoKenshi commented on src/main/java/org/example/QouterApp.java
> +import org.example.service.*;
ok

2023-11-08 10:52 UTC, kegisa requested changes

2023-11-08 10:52 UTC, kegisa commented on src/main/java/ru/popov/Main.java
> +        Rates rates = new Rates();
Здесь не ясно зачем это создавать, это же моделька просто, от нее не должен ни один класс зависеть

2023-11-08 10:52 UTC, kegisa commented on src/main/java/ru/popov/service/RatesGetterFromFile.java
> +    String path;
Модификаторы(

2023-11-08 10:52 UTC, kegisa commented on src/main/java/ru/popov/service/RatesGetterFromFile.java
> +    Map<String, Double> quoters;
зачем это хранить в классе если ты каджый раз из файла достаешь? либо так либо так

2023-11-08 10:52 UTC, kegisa commented on src/main/java/ru/popov/service/UserInput.java
> +public interface UserInput {
Распредели это все по пакетам, а то сейчас все в одну кучу сваленно. Инпут в пакет инпут, там будет интерфейс и реализации интерфейса и тд

2023-11-08 10:52 UTC, kegisa commented on src/main/java/ru/popov/MainLogicService.java
> +package ru.popov;
это тоже сервис , почему он не в пакете нужном?

2023-11-08 10:52 UTC, kegisa commented on src/main/java/ru/popov/MainLogicService.java
> +    private final Rates rates;
Это не зависимость, нужно убрать

2023-11-08 10:52 UTC, kegisa commented on src/main/java/ru/popov/MainLogicService.java
> +                rates.setBalance(balance);
не вижу смысла записывать то что ввел юзер в какую модель, это усложенние, просто передай потом этот интеджер в сервис конвертера и все

2023-11-08 10:52 UTC, kegisa commented on src/main/java/ru/popov/MainLogicService.java
> +                    continue;
continue не юзаются в реальной жизни, тут напрашивается выкинуть исключение какое то  и тогда вывод юзеру будет уже в catch

2023-11-08 10:52 UTC, kegisa commented on src/main/java/ru/popov/MainLogicService.java
> +                rates.setCurrency(typeCurrency);
Здесь тоже не ясно зачем это записывать в какую то модельку. Просто записал в строку, потом проверил что есть курс для такой валюты, взял его и передал в конвертер. если нет то кидаешь исключение

2023-11-08 10:52 UTC, kegisa commented on src/main/java/ru/popov/MainLogicService.java
> +                Map<String, Double> ratesList = ratesGetter.getCurrentRates();
Вот да, это примерно имел ввиду

2023-11-08 10:52 UTC, kegisa commented on src/main/java/ru/popov/MainLogicService.java
> +                    continue;
Здесь исключение лучше выкинуть

2023-11-08 10:52 UTC, kegisa commented on src/main/java/ru/popov/MainLogicService.java
> +                this.userInput.showToUser(String.valueOf(balance/ratesList.get(typeCurrency)));
Логику по делению я бы вынес в класс converter который на вход будет принимать сумму и курс и возвращать количество полученнйо валюты. Вроде так и было у тебя, надо было толко поправить.

2023-11-08 10:52 UTC, kegisa commented on src/main/java/ru/popov/service/RatesGetterFromFile.java
> +            System.out.println(e);
избавлйся от sout

2023-11-08 20:02 UTC, kegisa requested changes

2023-11-08 20:02 UTC, kegisa commented on src/main/java/ru/popov/input/ConsoleUserInput.java
> +    private Scanner scanner = new Scanner(System.in);
перевод строки

2023-11-09 05:33 UTC, kegisa requested changes

2023-11-09 05:33 UTC, kegisa commented on src/main/java/ru/popov/Main.java
> +        RatesGetter ratesGetter = new RatesGetterFromFile();
Здесь должен быть путь до файла, ак и было раньше

2023-11-09 05:33 UTC, kegisa commented on src/main/java/ru/popov/service/ConverterService.java
> +    public String convertCurrency(double balance, double currency){
А почему возвращаемый тип строка? кажется дабл должен быть

2023-11-11 15:23 UTC, merged